# Generated by Django 2.2.26 on 2022-06-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Study ID')),
                ('subject_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Study ID')),
                ('first_timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='First TimeStamp')),
                ('last_timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last TimeStamp')),
                ('content_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content Title')),
            ],
        ),
    ]
