# Generated by Django 2.2.26 on 2022-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220615_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject ID')),
            ],
        ),
    ]
