# Generated by Django 2.2.26 on 2022-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='is_game',
            field=models.BooleanField(default=False),
        ),
    ]
